# Generated by Django 5.1.7 on 2025-04-02 17:52

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mentorados', '0002_disponibilidadedehorarios'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DisponibilidadedeHorarios',
            new_name='DisponibilidadeHorarios',
        ),
    ]
